### ISSUE TITLE
What is the proper use of nativeReleaseVersion  

### ISSUE THREAD

**Issue by purringpigeon** [javafx-maven-plugin/javafx-maven-plugin#140]
Hello, 

I have placed my app.iss file into src/main/deploy/package/windows so that I can customize the settings of the generated installer.  (Main reason I moved to the zen java plug in) - but I am having an issue with nativeReleaseVersion  not being properly accessed during the build.

According to the documentation you are providing this as a variable to the build process: 

*The release version as passed to the native installer*

I posted at the INNO forums and was given two ways to access this:

    OutputBaseFilename=myapp-installer-{#nativeReleaseVersion} - but this aborts the project set up.
    OutputBaseFilename=myapp-installer-{#GetEnv("nativeReleaseVersion")} - but this returns blank.

I would like to be able to get the current project build into that during the process, with my customized ISS file.  Do you know if this is supposed to work the way I am using it?

    <plugin>
				<groupId>com.zenjava</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>8.1.3</version>
				<configuration>
					<mainClass>com.mycompany.myapp</mainClass>
					<verbose>true</verbose>
					<bundler>EXE</bundler>
					<additionalAppResources>${project.build.directory}/additionalResources</additionalAppResources>
					<nativeReleaseVersion>0.0.0.1</nativeReleaseVersion>
				</configuration>
    </plugin>

**Comment by FibreFoX** [comment]
https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L151

Did you try to set `<nativeReleaseVersion>` as `0.0.1` (three digits instead of four)?

**Comment by purringpigeon** [comment]
Yes I tried it that way first, then noticed that it might be 4 on the INNO site, so I tried that.  It just comes up as blank.

**Comment by FibreFoX** [comment]
Hm .... interesting, I will investigate this.

**Comment by FibreFoX** [comment]
I assume you did use your very own file without using generated one (shown via verbose-mode).

The used one by java-packager [can be viewed here](https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/resources/com/oracle/tools/packager/windows/template.iss)

When providing custom installer-file, please take care of the original javapackager/javafxpackager-process, taking a look at the openjfx-sources often helps more than searching for "why is this not working" (this is how I myself try to find the bugs/workarounds): https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/windows/WinExeBundler.java

What happens when you just set `<nativeReleaseVersion>` and not providing your custom file?

**Comment by purringpigeon** [comment]
In this case I get the correct version number, with the standard defaults. With the version number statically referenced. 

However, I would like to fine tune the installer. I was just checking to see if my use of the argument was correct. Just wanted to know if I can use a customized file with dynamic elements provided by the plug in. 



On Jul 29, 2015, at 12:13 PM, Danny Althoff <notifications@github.com> wrote:

I assume you did use your very own file without using generated one (shown via verbose-mode).

The used one by java-packager can be viewed here

When providing custom installer-file, please take care of the original javapackager/javafxpackager-process, taking a look at the openjfx-sources often helps more than searching for "why is this not working" (this is how I myself try to find the bugs/workarounds): https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/windows/WinExeBundler.java

What happens when you just set <nativeReleaseVersion> and not providing your custom file?

**Comment by FibreFoX** [comment]
To be clear: this is not the part of javafx-maven-plugin, its the javapackager itself :smile:

All this plugin does, it fills the provided configuration-parameter into a special map and fills them into the packager, if something does not work, it's because the javapackager does not like it.

It is possible to customize your file, but it's not intended to have automated maven-properties inside it. All possible replaceable values are within that `template.iss`-file some comments above.

To customize your installer-filename, check [this property](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L187), you can change this to a appropiate name (and having maven to replace some values in it), make sure to change your files under the `src/main/deploy`-folder.

**Comment by purringpigeon** [comment]
Thanks - I will give it a shot.  I am looking for the template.iss at the moment, and will see if I can make the needed tweaks to it and let it be generated each time.  If not, we will just update the label with each build in the iss file directly, if we can't set the template to be generic enough for different builds.  Thank you.

**Comment by FibreFoX** [comment]
If you have further results, would be nice to have that feedback here reported, and if possible ;) close the door/ticket behind you.

**Comment by purringpigeon** [comment]
Will do - I appreciate your help on this.  It's almost where I need it.  Struggling now with the template.iss - not sure how/where to override it...  But if it doesn't work, I will simply go for manual update to the custom.iss file that I was using before.

**Comment by FibreFoX** [comment]
Maybe this is a bit hacky, but you could process that file via maven by putting it into generated `<additionalAppResources>`-folder, but you have to put that file into another src-folder :) but should provide all your needs.

That files are processed before the javapackager is called.
https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L262

What do you think about this?

**Comment by purringpigeon** [comment]
Thanks!  Will give it a whirl.
