### ISSUE TITLE
jfx:run cli arguments

### ISSUE THREAD

**Issue by dmitry-izmerov** [javafx-maven-plugin/javafx-maven-plugin#176]
Would be great to add process of cli arguments from settings of this plugin.

**Comment by FibreFoX** [comment]
Could you specify your question a bit more?! I don't understand it :sweat:, maybe some example what you want to have would be nice.

**Comment by dmitry-izmerov** [comment]
I want to pass cli arguments to application when I launch command jfx:run. Now I use command jfx:jar, pass arguments to got jar - java -jar ApplicationName arg1 arg2 ...

**Comment by FibreFoX** [comment]
Now I understand, but the clear answer is no. The problem comes with the method `jfx:run` is working:
it is a shortcut for calling the main-class via `org.codehaus.mojo:exec-maven-plugin` and there are multiple problems: it isn't how the consumer would call your application.

Another problem comes with native launchers, which might have special JVM-settings and pre-set arguments and some JVM-properties.

All in all this way produces way too much false-positives, as the preloader is skipped too, that are the reasons I deprecated the run-mojo in the last releases. It might be slowing your development-process, but its the better way to have correct results of your application.

**Comment by FibreFoX** [comment]
As the exec-maven-plugin is not used by this plugin anymore, this becomes a valid issue now. Will be added soon.
@dmitry-izmerov If you don't use this tool anymore, please ignore this message  ;)
