### ISSUE TITLE
Add libs to jar

### ISSUE THREAD

**Issue by codewing** [javafx-maven-plugin/javafx-maven-plugin#179]
Hey,
I'm wondering if there exists an option to automatically add the libs into the generated jar so everything looks cleaner.

**Comment by FibreFoX** [comment]
Nope, and it will never exist. There is a good reason we are putting the libs aside of the jfx-jar. That question targets to a fat-jar, but this has more than one problem.

Just references:
https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/177#issuecomment-171638597
https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/3

NOT merging all dependency-jars might not be a solution with very few files, but it is the cleanest way, because of no existing drawback.
