### ISSUE TITLE
Missing artifact javafx-packager

### ISSUE THREAD

**Issue by pahofmann** [javafx-maven-plugin/javafx-maven-plugin#187]
When adding `javafx-maven-plugin` in eclipse I get the following error:
`The container 'Maven Dependencies' references non existing library 'C:\Users\MyUser\.m2\repository\javafx-packager\javafx-packager\1.8.0_20\javafx-packager-1.8.0_20.jar'`

I`m using JDK 1.8.0_72.

**Comment by FibreFoX** [comment]
Could you provide some reproducable project? What version of eclipse are you using?

Eclipse isn't the best when resolving dependencies, already got some issue about that, see #143

**Comment by pahofmann** [comment]
I'm using eclipse Mars.2 Release (4.5.2).
The error occures even if when I just start a new project and add `java-maven-plugin` in the pom.xml.

**Comment by FibreFoX** [comment]
@pahofmann sorry to be annoying, but I need a project to confirm your problem :smile:

**Comment by pahofmann** [comment]
I created a new test project and added `java-maven-plugin`
https://owncloud.pahofmann.com/index.php/s/vinafLJlR02GKhP

**Comment by FibreFoX** [comment]
Hi @pahofmann, you are using the plugin wrong. Instead of putting this to your dependencies, please take a look at the readme:
> Add this to your pom.xml within to your build-plugin

You have to add that maven-PLUGIN to your build-configuration (simple example: https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/it/02-cli-jfx-jar/pom.xml#L33 )
