### ISSUE TITLE
Minimize JRE in native bundle 

### ISSUE THREAD

**Issue by malafeev** [javafx-maven-plugin/javafx-maven-plugin#199]
Native bundle contains entire JRE.
Could you add feature to exclude packages, classes, jars etc?

Java 9 will come only next year :(

**Comment by FibreFoX** [comment]
@malafeev This reminds me to [another stackoverflow-post](http://stackoverflow.com/questions/36538200/reducing-the-size-of-my-natively-deployed-javafx-application/36570931#36570931) I've encountered last days.

There are some licence restrictions about stripping, or to be more specific to distribute a stripped down JRE: http://www.oracle.com/technetwork/java/javase/jre-8-readme-2095710.html

But it isn't required to change anything from the side of the javafx-maven-plugin, because that feature is already there :smile_cat: ! By setting some [bundleArgument](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/30b56fff864dc8ec05b302e62c29e7ae9d000289/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L192) you can specify your own runtime:

```xml
<configuration>
    <!-- some settings -->
    <bundleArguments>
        <runtime>[some path to custom stripped down JRE]</runtime>
    </bundleArguments>
</configuration>
```

There is another solution I'm currently working on, which includes the usage of [launch4j](http://launch4j.sourceforge.net/), but this requires some more free time than I'm currently having.

But nevertheless this question should be answered without any modification of the javafx-maven-plugin.

**Comment by algakzru** [comment]
Here is a nice article about reducing the jre size - http://blog.gerardin.info/archives/799
