### ISSUE TITLE
Classpath for log4j xml

### ISSUE THREAD

**Issue by dmusican** [javafx-maven-plugin/javafx-maven-plugin#207]
I'm using this wonderful plugin to create an executable jar that contains within it an xml file with config information for log4j. When executing the jar file, the xml config file can't be found. My best guess is that this is because while the xml file does end up landing in the jar file, it isn't in the classpath contained within that jar file. (I'm not 100% sure this is what is going on, but I thought I'd start here.) Is there some known easy fix / issue associated with trying to read files from within the created jar file?

**Comment by FibreFoX** [comment]
Hi @dmusican ,

you are talking about that [file not found issue](https://github.com/dmusican/Elegit/issues/122) on your [Elegit-project](https://github.com/dmusican/Elegit/), right?

I will try to reproduce it, maybe it's just some trivial "file X has to be on folder Y"-thing instead of a bug of this maven-plugin :smile_cat:

**Comment by FibreFoX** [comment]
@dmusican 

Hi, this is no issue with the javafx-maven-plugin, it is some problem with your application-logging. I will make a pull-request to that project to fix logging.

By the way, this will NEVER work:
```
System.setProperty("logFolder", getClass().getResource("/elegit/logs").getPath().toString());
```
You are generating some path into a JAR-file, which isn't writable as a normal folder on your harddrive. It generates something like this (which isn't valid):
` file:/C:/someFolders/Elegit/target/jfx/app/Elegit-1.0-SNAPSHOT-jfx.jar!/elegit/logs/elegit.log`
