### ISSUE TITLE
'Mvn clean' don't clean temporary folder (Mac OSX)

### ISSUE THREAD

**Issue by timoreichen** [javafx-maven-plugin/javafx-maven-plugin#216]
Running 'mvn install' command all goes fine. 'mvn clean' though does not clean formerly created temporary files.

In my system the temporary files are created under /var/folders/kh/somelongnumberfolder/T

This folder is filled with files called +JXF17516932839903047.tmp
Also you find folders called fxbundler461158345227923059 with content:
images 
macosx
packages

So, after building native packages several times the disk-space is filled up with the above
files and folders. 

System Mac: 10.11.5
Javafx-maven-plugin: 8.5.0
JDK: 1.8.0_91

**Comment by FibreFoX** [comment]
Hi @timoreichen, this is no bug of the javafx-maven-plugin, because this is done by the [macosx bundler from the JDK](https://github.com/teamfx/openjfx-8u-dev-rt/blob/fd634925571310284b02d89ff512552e795ba5e8/modules/fxpackager/src/main/java/com/oracle/tools/packager/mac/MacAppBundler.java#L554).

if you set `<verbose>false</verbose>`, this folder should get cleaned up.
