### ISSUE TITLE
Native configuration equivalent for "-native image"

### ISSUE THREAD

**Issue by shoon** [javafx-maven-plugin/javafx-maven-plugin#241]
I'm looking for a way to emulate the "-native image" option in the javapackager. That is, the plugin will build only the OS-specific .app or disk image without continuing on to the deb/rpm/pkg/msi. 

The <bundle> configuration seems to default to the equivalent of "-native all" and you can only specify a single bundle override (mac.app, linux.app, or windows.app) but the commandline "image" determines the OS during runtime.

Is there a configuration to achieve the same thing as the commandline "-native image"?

**Comment by FibreFoX** [comment]
Hi @shoon , you can specify single bundler by setting this to the plugin-configuration:
```
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.7.0</version>
    <configuration>
        <mainClass>com.zenjava.test.Main</mainClass>
        <bundler>win.app</bundler> <!-- other names are "mac.app" and "linux.app" -->
    </configuration>
</plugin>
```

**Comment by FibreFoX** [comment]
If this is working for you, please close this issue.

**Comment by shoon** [comment]
Yes, I see the single bundler override but that will only build a single os-specific bundler for that pom. 

The "image" option on the commandline builds the native app for that maven node without having to hard code it in the pom - windows.app for windows, linux.app for linux, etc.

The only way this could be used if there was a way to configure multiple bundlers (windows.app, mac.app and linux.app) in a single pom but the NativeMojo doesn't appear to support that.

It would be great if there were higher-level abstraction for the bundler configuration that maps to the javapackger -native argument:

- all: Runs all of the installers for the platform on which it is running, and creates a disk image for the application. This value is used if type is not specified.
- installer: Runs all of the installers for the platform on which it is running.
- image: Creates a disk image for the application. On OS X, the image is the .app file. On Linux, the image is the directory that gets installed.

http://docs.oracle.com/javase/8/docs/technotes/tools/unix/javapackager.html

**Comment by FibreFoX** [comment]
I do understand your problem, but I fear this will get dropped, the corresponding ENUM is deprecated:
https://github.com/teamfx/openjfx-8u-dev-rt/blob/33d8ed8c4dffab63bbb5d2b5e8fce347ddf504b8/modules/fxpackager/src/main/java/com/sun/javafx/tools/packager/bundlers/Bundler.java#L28

You can use maven-profiles for OS-specific bundler-configurations, personally I do not recommend your idea, because every bundler works different and you are loosing some control about it, especially when using "special options".

The `<bundlerType>` got dropped since 8.4.0, it was already deprecated in [8.3.0](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/javafx-maven-plugin-8.2.0/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L95), but it seems that I missed to mention this inside the release-notes.

This is no "just change ant with maven"-replacement, a lot of ideas are not really nice with the current `javapackager`, and especially configuration of OS-specific things should be handled via your build-system (like OS-activated profiles)
