### ISSUE TITLE
Option to extend Class-Path property in JAR manifest file

### ISSUE THREAD

**Issue by mxbyrd** [javafx-maven-plugin/javafx-maven-plugin#247]
Hello.

I'm working on plugin system support for my app. The idea is that the all plugins JARs should be placed into "plugins/" folder right near main app JAR.

```
/myapp
--lib/
----dependency1.jar
...
----dependencyN.jar
--plugins/
----plugin1.jar
...
----pluginN.jar
--myapp.jar
```

After that I'm going to load them via [ServiceLoader](http://docs.oracle.com/javase/6/docs/api/java/util/ServiceLoader.html). For this purpose I need to add an entry to the JAR manifest "Class-Path" property. The problem is that I can't find any option to add smth to the JAR manifest file by using **javafx-maven-plugin.** It looks like you've implemented only an option to exclude JARs from classpath, but not to include them.

I also tried to use **maven-jar-plugin** but didn't succeed.

```
<archive>
    <manifestEntries>
        <Class-Path>plugins/</Class-Path>
    </manifestEntries>
</archive>
```

I think I can just use `-classpath` CLI option, but executable JAR is more preferred option.

**Comment by FibreFoX** [comment]
Hi there,

this is something why I added that exclusion-feature ;) funny that it really gets used by someone.

I would suggest to not have these plugins as part of the classpath, you should scan that folder manually and add all of them separately to the current classloader.

The jar-file generated by the javafx-maven-plugin (or more precise: by the javapackager) does not respect anything done with the maven-jar-plugin!

As far as I understood, the classpath has to target jar-files, and not just folder-names.

I'm using something like this:
```java
for( String pluginFileName : pluginFolder.list() ){ // pluginFolder is from type java.nio.file.Path
    logger.log(Level.INFO, "Installing bundle-file: {0}", new Object[]{
        pluginFileName
    });
    File pluginFile = new File(pluginFolder, pluginFileName);
    bundleContext.installBundle(pluginFile.toURI().toString());
}
```

Instead of using OSGi, you just can add that found jar-file to the classloader ([like it is done inside this plugin](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/20c92c3967960c8c22c78022afb2802c3886db14/src/main/java/com/zenjava/javafx/maven/plugin/AbstractJfxToolsMojo.java#L128)).

**Comment by FibreFoX** [comment]
one note about the manifest-entries:
https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/main/java/com/zenjava/javafx/maven/plugin/JarMojo.java#L92

Just use that configuration property within the configuration-block of the javafx-maven-plugin. It's going to be used while generating the jfx-jar.

**Comment by mxbyrd** [comment]
Unfortunately OSGI is not an option because it [breaks Maven dependency system](http://stackoverflow.com/a/14926624).

I've searched for this question a lot and found 3 approaches:
1. Use [Reflection API hack](http://stackoverflow.com/a/1011126) to add JAR url to the system classloader. Right exactly as you pointed out.
2. Extend URLClassLoader and pass that object to the `ServiceLoader.load()` method 

```
public class PluginClassLoader extends URLClassLoader {/*...*/}

PluginClassLoader pcl = new PluginClassLoader(new URL[] {/* JAR URLs here */});
for (Plugin plugin : ServiceLoader.load(Plugin.class, pcl)) {
    //...
}
```

3. Write a shell (or batch) script to recursively scan plugin folder for JAR files, and use these files to generate classpath option.

I don't know which of these options is the best, for now at least. Maybe I should try all of them. Anyway I think that the ability to add entries to the classpath manifest (generated by javafx-maven-plugin) will be very useful.

Much thanks for your help!
