### ISSUE TITLE
plugin configuration page is unclear

### ISSUE THREAD

**Issue by teefal** [javafx-maven-plugin/javafx-maven-plugin#250]
Whenever I go to http://javafx-maven-plugin.github.io, I have a simple goal ... read the API for all possible parameters.  The way it's shown now, it's not clear what the params are.

A few don't have header names with gray lines: needShortcut, needMenu

One appears to be missing the name altogether:  "JVM Flags to be passed into the JVM at invocation time. These are the arguments to the left of the main class name when launching Java on the command line."

I also appear to need to click several of the wizard options to get all the parameters to show, leaving me with the feeling that I don't quite have all the parameters.

More useful than a wizard would be a simple list of all the parameters, like a javadoc.

**Comment by FibreFoX** [comment]
That website is not intended to replace any "documentation", it is ment to create some configuration via clicking. And it is not fully implemented, I'm already on it :/

To get a full view of parameters, just call `mvn jfx:help -Ddetail=true -Dgoal=<goal-name>` to have full maven help pages.

Having javadocs is somewhat ... not fitting, because you won't need java-documentation ;) all you need is already inside your maven-setup.

**Comment by teefal** [comment]
Wow, there's a lot more there than I knew.  Putting that command on the readme page might help others too.

**Comment by FibreFoX** [comment]
;) you are welcome, and this will get into a new documentation/readme/website ... the problem is, that my other two project-collegues (zonski and maxd) are not active on this project, and my spare time is really limited, but I have a bit time the next days until the new year, so after fiddeling a bit with VUE I might get some new configuration-creation website online hopefully this year (and it is a real pain that I write this too much ...). But hopefully the maven-command helps you out meanwhile.

**Comment by teefal** [comment]
quick question ... this doesn't show preLoader when I do mvn jfx:help -Ddetail=true -Dgoal=native

My preloader no longer works, so I'm working on this too.

**Comment by FibreFoX** [comment]
PreLoaders are some heavy topic for native bundles, the prefered solution is to not use them and have a small loading window instead. Leaving some links for documentation purpose:
https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/80
http://stackoverflow.com/questions/15126210/how-to-use-javafx-preloader-with-stand-alone-application-in-eclipse
https://blog.codecentric.de/en/2015/09/javafx-how-to-easily-implement-application-preloader-2/

Please note that calling `mvn jfx:run` tries to execute that generated jar-file, because of the bootstrapping of javafx (because that jar-files behaves different from directly opening the application inside the IDE)

**Comment by teefal** [comment]
So you're saying that the preLoader attribute is no longer there?

I had a working preLoader using your plugin at one point.  Trying to determine what changed.

**Comment by teefal** [comment]
Ah, never mind, your jfx:run showed an NPE in my loader.  Thanks.

**Comment by teefal** [comment]
Tried using the JVM splash param as in ...

<jvmArg>-splash:splash.png</jvmArg>

This worked on Mac, but not Windows.  The splash.png file is in the bundle, under "app".  Both JRE's are the most current Oracle JVM.  Thoughts?

**Comment by FibreFoX** [comment]
Are you sure it does not work? maybe its too quick, but this topic is a bit confusing on its own.
https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/javafx_ant_task_reference.html#CACDIDFE
> Passes the location of the image to be used as a splash screen. Currently custom splash images can only be passed to Web Start applications, and use of this parameter has no impact on standalone applications or applications embedded into web pages.

**Comment by teefal** [comment]
Ah, no, that's the webstart one.  I did a JVM -splash param ... https://docs.oracle.com/javase/8/docs/api/java/awt/SplashScreen.html

Again, this works in Mac.

**Comment by FibreFoX** [comment]
You are not the only one who has problems with this:
https://github.com/FibreFoX/javafx-gradle-plugin/issues/35
https://bugs.openjdk.java.net/browse/JDK-8087431
https://bugs.openjdk.java.net/browse/JDK-8091654

My tip: you should make your own preloader/splash-screen window, makes it alive cross-system.

**Comment by teefal** [comment]
Bummer. Thanks for the pointers.  I did have a preloader splash screen, but it took too long to load.  Will go back to that now.  Thanks again.
