### ISSUE TITLE
useSystemInstall or shouldLaunchAfterInstall parameter

### ISSUE THREAD

**Issue by teefal** [javafx-maven-plugin/javafx-maven-plugin#251]
I need to prevent Windows from launching my app after it installs.

The ant docs appear to have a param that sort of does this ...

<fx:preferences> / install = true

If you chose system-wide installation, then the user will need to have admin permissions, and the application will not be launched at the end of installation.

Can you expose this or find some other way to tell Windows not to launch after install?

**Comment by FibreFoX** [comment]
This is already possible via special bundleArgument:

```xml
<configuration>
<!-- other stuff -->
    <bundleArguments>
        <startOnInstall>true</startOnInstall>
    </bundleArguments>
</configuration>
```

**Comment by FibreFoX** [comment]
Just one side-note: all these "bundleArguments" are not documented ... nor by this plugin nor by oracle itself, I always seach inside the sourcecode to find these values ... thats highly frustrating, but might be covered some time when I get the time to REALLY create some documentation.

**Comment by FibreFoX** [comment]
Hm ... that `<startOnInstall>` might not be it, please check this, I'm searching from my end again ...

**Comment by teefal** [comment]
This didn't work...

                    <bundleArguments>
                       <startOnInstall>false</startOnInstall>
                    </bundleArguments>

**Comment by FibreFoX** [comment]
Hm, it seems this is not possible anymore ... some excerpt from the `template.iss`-file:
```
[Run]
Filename: "{app}\RUN_FILENAME.exe"; Parameters: "-Xappcds:generatecache"; Check: APPLICATION_APP_CDS_INSTALL()
Filename: "{app}\RUN_FILENAME.exe"; Description: "{cm:LaunchProgram,APPLICATION_NAME}"; Flags: nowait postinstall skipifsilent; Check: APPLICATION_NOT_SERVICE()
Filename: "{app}\RUN_FILENAME.exe"; Parameters: "-install -svcName ""APPLICATION_NAME"" -svcDesc ""APPLICATION_DESCRIPTION"" -mainExe ""APPLICATION_LAUNCHER_FILENAME"" START_ON_INSTALL RUN_AT_STARTUP"; Check: APPLICATION_SERVICE()
```
Corresponding lines from `WinExeBundler.java` of the OpenJDK 8:
```java
        data.put("APPLICATION_SERVICE", SERVICE_HINT.fetchFrom(params) ? "returnTrue" : "returnFalse");
        data.put("APPLICATION_NOT_SERVICE", SERVICE_HINT.fetchFrom(params) ? "returnFalse" : "returnTrue");
```

This means that you need to use your customized installer-template-file where these RUN-parts are removed. For MSI-installers I'm checking now.

**Comment by teefal** [comment]
How about the other property that has the effect of turning that off ...

fx:preferences / install = true

Can I set this?

**Comment by FibreFoX** [comment]
Does this still work? Can you point me to the documentation for this?

**Comment by FibreFoX** [comment]
After checking: this does not exist on MSI-installer, assuming you mean EXE-installers ;)

**Comment by teefal** [comment]
Yes, EXE.  https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html

**Comment by FibreFoX** [comment]
Oh, you are only looking for the scope, I thought it was about the "run after install", this can be archieved with this:

```xml
<configuration>
    <!-- other stuff -->
    <bundleArguments>
        <systemWide>true</systemWide>
        <!-- bonus: for making the user to choose the installation-target folder -->
        <installdirChooser></installdirChooser>
    </bundleArguments>
</configuration>
```

**Comment by FibreFoX** [comment]
@teefal to clear some things: making the bundle requiring system-wide installation is done via `<systemWide>` argument, but this does not make the application to not start after installation, for this you are required to adjust the used template (please make sure to have `<verbose>` set to true, as you will not get your own installer-script otherwise).

**Comment by teefal** [comment]
Hi, can't seem to figure out what you mean by "This means that you need to use your customized installer-template-file where these RUN-parts are removed."

Are you talking about adding something the wsf customization script, or modifying the .cfg file somehow?

**Comment by teefal** [comment]
Or are you saying I should do something like this in the pom ...

<serviceHint>false</serviceHint>

**Comment by FibreFoX** [comment]
Nope :) as this is "just" a nice wrapper around the [javapacker](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javapackager.html) itself, its powers are inherited. Let me make a quick example what I mean:

If you are creating native bundles, lets say installers, several toolsets are used, like WiX or InnoSetup on Windows-systems. These toolsets are requiring some "setup-description" files to create the installer-files, and for each bundler (EXE and MSI have separate ones) there is some template which gets used, you can find them here: https://github.com/teamfx/openjfx-8u-dev-rt/tree/master/modules/fxpackager/src/main/resources/com/oracle/tools/packager/windows/ (no official repository of oracle). When you have `<verbose>true</verbose>` these pre-filled templates, which are used for installer-generation, are NOT removed (if `<verbose>` is set to `false`, they are getting cleaned up), you should have something like this inside your build output for each bundler:
```
Config files are saved to C:\Users\YourUserName\AppData\Local\Temp\fxbundler5437195451701938726\windows. Use them to customize package.
```
If you go to that folder, you will see some files with the name `<appName>.wxs` or `<appName>.iss` (depending on what bundler did run). You can copy these files to `src/main/deploy/package/windows` (because anything below `src/main/deploy/` will be added to classpath for the bundler, the "package" and "windows"-folder come from the javapackager itself).

So you can adjust/modify the installer in every possible way, but you might want to compare that file against the template being used for generating it, you might want to use the [InnoSetup-template](https://github.com/teamfx/openjfx-8u-dev-rt/blob/master/modules/fxpackager/src/main/resources/com/oracle/tools/packager/windows/template.iss) or [WiX-template](https://github.com/teamfx/openjfx-8u-dev-rt/blob/master/modules/fxpackager/src/main/resources/com/oracle/tools/packager/windows/template.wxs) itself as your files, because if you change something, lets say the appName, you would have to replace a lot of entries inside these files. So using the original template as your custom template, by only doing minimal adjustments should work out for you.

This means that if you remove the `[RUN]`-part inside the template should do the trick of not running the application after installation is done, while still have [the settings I wrote above](https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/251#issuecomment-268869985)

**Comment by teefal** [comment]
Thanks.  This did the trick.  Thanks for the lengthy explantation.

**Comment by FibreFoX** [comment]
@teefal happy that it worked out for you :) is this issue now closable?

**Comment by teefal** [comment]
sure, thanks.
