### ISSUE TITLE
How I implement auto update project?

### ISSUE THREAD

**Issue by arthurcvm** [javafx-maven-plugin/javafx-maven-plugin#288]
Hi, I need a auto update project, but the web start not is compatible with Maven project, what I solve this?

**Comment by FibreFoX** [comment]
How does this relate to this maven-plugin? Creating JNLP-files are created by the javapackager, the whole "how to update my javafx-deployment" question is not related to this plugin.

WebStart is represented via JNLP-files, which ARE created with this plugin, but is there any problem? If so, please return with a reproducable project.

**Comment by arthurcvm** [comment]
But I want use a native builder or this don't possible?

**Comment by FibreFoX** [comment]
How does webstart and native bundle have something to do with each other? Maybe you can elaborate your scenario a bit?

**Comment by JustGregory** [comment]
Arthur, almost every developer would love to have a predefined library to implement auto-updating of their app. But the simple answer is that each developer needs to implement updating in their own individual way.

... that being said, the *how to* of implementing an update function might be given in plenty of examples around the Internet, and if not then I have a few ideas. It is not so difficult to understand how to do this once you have the experience, but the first time or two that you implement one like it, you may have some confusion.

**Comment by arthurcvm** [comment]
I'm having a daydream, I will solve, I will draw up a launcher to be compatible with the plugin and make available to the community, I love this plugin, I don't want to leave him and even your community.

**Comment by FibreFoX** [comment]
We are talking about "AUTO" update, right? Lets share some of my thoughts about this:

The first question here is: how does the application detect that its outdated? Mostly there is some webserver around on your download-website, where the application can check against some hard-coded version, or some file-checksum (e.g. antivirus-software checks against file-hashes because versioning isn't always the best for this). After auto-detection of a new version, there often is some hint like popup on application-start, or even a scheduled background-application which does popup a window for this.

The next step: how to get this new version? Please keep in mind that not every user is connected with a decent link to high-speed internet, maybe they installed your application from a DVD (some tech-magazine or something like that) or when having a fast connection. In the case your application will have the ability to automatically download the "update"-package, please make it able to disable by the users, as it is their choice to change their installed files.
Another thing to have in mind: not every user is allowed to install new applications. On windows there are registry-entries which have to be added/changed/removed, but this conflicts against corporate AD rules, where every access to this vital place is restricted.

The next step: how to "update" your files? This depends on the platform! All installers created with the `javapackager`/javafx-maven-plugin having their own rules about "newer version" .... and you have a lot of restrictions, which are nearly to not being possible handle with a common configuration. Please remind that your "distributed application" contains the JRE, your tiny piece of app, a lot of dependencies (probably) and the part of the installer. With MSI-installer it is possible to setup some UpgradeCode, which is for detecting an old installation of the same application. Other installers might do something different here, but their way of doing this is different for each one of them.

If you enable "auto-update" in your application, you have to think a bit bigger that just "I want to always have my latest version of the app", because everything has to be "nice" for all players in the game: the users, the system administrators and the hardware-equipment or internet-connection.

The JNLP-/Webstart-way just does exactly all the stuff, but you are not really "installing" your application, which destroys all the effort of sharing the app.

Another ugly self-backed way would be to only distribute a "launcher" which contains some server-adress where to download the real payload .... ehm ... realy application ;) but on Mac it is restricted to NOT download some application and Apple won't let you into the appstore.

To conclude: no, there is no "already solved way" to handle something we always call "auto-update".

**Comment by FibreFoX** [comment]
@arthurcvm maybe you want to check this her: https://github.com/edvin/fxlauncher

Haven't looked into it, but maybe it is what you searched for

**Comment by arthurcvm** [comment]
the fxlauncher is not customize, look my issue: https://github.com/edvin/fxlauncher/issues/67

**Comment by FibreFoX** [comment]
Do you have any public project here on github or anything? Please keep in mind that for reproducing some bug or anything, maintainers need to have some project to tinker with ... your project might be just "misconfigured". As the fxlauncher is only a jar-file, this has nothing to do with the icon.

**Comment by arthurcvm** [comment]
I configure the project equals the instructions of javapackager indicates in the fxlauncher, but the icon bar don't modify.

**Comment by phidias51** [comment]
Maybe I'm missing something here, but if you want auto update capabilities AFAIK, there are 2 ways of delivering it:
(1) Use the platform's native app store (i.e. Apple's App Store, and the Windows, and Ubuntu/RedHat equivalent).
(2) Use JNLP for installs

Both of those approaches are solvable with the java packager and the associated build tools. If there's a  specific problem, it would help to see the build file and the error.

**Comment by FibreFoX** [comment]
@phidias51 for Windows and Debian/Ubuntu there is no "app store" ;) even with the window app store, because they want UWP-apps

@arthurcvm if you can't provide a project where I or the other project maintainers can reproduce this, you will be out of luck
