### ISSUE TITLE
Add version to the native executable

### ISSUE THREAD

**Issue by FDelporte** [javafx-maven-plugin/javafx-maven-plugin#292]
When you right click an exe file, there is a list of usefull values, of which we want at least the version to fill in. Is this (or will this be) possible with javafx-maven-plugin?

![image](https://cloud.githubusercontent.com/assets/1415873/25848377/5e9dbd82-34ba-11e7-90d7-f5e81d172af9.png)

**Comment by FibreFoX** [comment]
The exe-file comes from the javapackager, will have to check this, not sure about. Maybe there already exists some more-or-less hidden switch.

**Comment by FibreFoX** [comment]
As far as I understand the "win.app"-bundler, this is not possible. But you might want to create some native launcher yourself containing these information and then providing that file to the javafx-maven-plugin.

```xml
<bundleArguments>
    <win.launcher.url>file:///C:/your%20path%20to%20your%20binary/launcherWithCopyright.exe<win.launcher.url>
</bundleArguments>
```

But to be honest ... you are not looking at the right thing. The native launcher is some regular file, which DOES NOTHING than booting the JVM and pushing some options into it. Instead of modifying that exe-file, think about a manifest-entry inside the jfx-jar.

**Comment by FibreFoX** [comment]
You can compile that exe-file yourself, just look at the source-code ;)
https://github.com/teamfx/openjfx-8u-dev-rt/blob/master/modules/fxpackager/src/main/native/launcher/win/WinLauncher.cpp

**Comment by FDelporte** [comment]
OK, thanks for the quick reply! 
Indeed the manifest-entry seems a better approach.
So no issue and can be closed!
