### ISSUE TITLE
[question] Is there a way to produce a fat jars

### ISSUE THREAD

**Issue by HerbertKoelman** [javafx-maven-plugin/javafx-maven-plugin#304]
Hello,

Is there a way to create a fat jar ? I wondered if I could avoid the `./lib` directory that is created when I run `mvn package`.

Regards

**Comment by FibreFoX** [comment]
Hi @HerbertKoelman ,
there is no support for fat-jar, and there wont be anymore. The problem comes with duplicated files and especially with signing. If you want to distribute your application, just create some ZIP-file from the generated folder.

To be clear on this topic (as this is requested far more than good for jfx-projects): there won't be fat-jar support from this plugin.

**Comment by HerbertKoelman** [comment]
Makes sense.

Thanks for this (very) rapid answer :-)

**Comment by ennerf** [comment]
You can however create a fat jar called ${project.build.finalName}.jar in the step before and skip copying dependencies to lib/

<updateExistingJar>true</updateExistingJar> <skipCopyingDependencies>true</skipCopyingDependencies>

Ran into the same problem before.

**Comment by HerbertKoelman** [comment]
I see, would you consider sharing a sample pom.xml that just does what you suggested ?

Regards

**Comment by ennerf** [comment]
https://gist.github.com/ennerf/55838933a15e019d9e62cbac3a2d0304

Not entirely complete, but it should get you started.

**Comment by HerbertKoelman** [comment]
Hey ! That's great, this should get me started indeed. 

Thanks

Herbert

(Sorry for the late reply, your mail was dumped in my spam folder 👀)
