### ISSUE TITLE
Preloader is not working with 8.1.2 plugin.

### ISSUE THREAD

**Issue by Anvay-webonise** [javafx-maven-plugin/javafx-maven-plugin#80]
we are using preloader for splash screen and its working perfectly fine with 2.0 plugin(with java 7) now with 8.1.2 (java 8) its not working.
.msi gets generated but splash screen is not working.

**Comment by FibreFoX** [comment]
I came across this issue myself, but **its not an issue of this maven-plugin**, its more a problem with the generated exe-file (which comes from javafxpackager). The problem is, as far as i understood the discussion, known but not really dealt with:
http://mail.openjdk.java.net/pipermail/openjfx-dev/2014-January/012296.html

But there is another thing i am confused with: when using ```mvn jfx:run``` the preloader is skipped, just by running the generated xyz-jfx.jar itself the preloader is executed.
See: https://github.com/zonski/javafx-maven-plugin/blob/master/src/main/java/com/zenjava/javafx/maven/plugin/RunMojo.java#L84

**Comment by FibreFoX** [comment]
This is closed, because its not handled within javafxpackager/native package app. Showing a splash-screen should be possible, but preloader are capable of more (http://stackoverflow.com/questions/15126210/how-to-use-javafx-preloader-with-stand-alone-application-in-eclipse).

I must admit, this is something very undocumented, but please re-open if you found an working example using native javafxpackager-tools.
